language: generic
sudo: required
services:
    - docker
    
before_install:
    - docker build -t stheunissen/docker-react -f Dockerfile.dev .
    
 script:
    - docker run -e CI=true stheunissen/docker-react npm run test
    
